import { type ChunkFrame, type WorldSeed, ringToWkt } from '@civ/core'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
export const SEED_DIR = join(HERE, '..', '..', 'client', 'public', 'world')
export const SQL_DIR = join(HERE, '..', '..', 'persistence', 'seed')

/**
 * §21.4: the emitter hands back what it wrote, re-read from disk, not the
 * object it was given. Millimetre quantisation happens in `JSON.stringify`, so
 * anything validating the argument is validating a value that never reaches a
 * consumer. The caller gets the artifact.
 */
export async function emitSeed(
  seed: WorldSeed,
): Promise<{ jsonPath: string; bytes: number; written: WorldSeed }> {
  await mkdir(SEED_DIR, { recursive: true })
  const jsonPath = join(SEED_DIR, `${seed.chunk.id}.json`)
  const text = JSON.stringify(seed, roundNumbers)
  await writeFile(jsonPath, text)
  await writeFile(
    join(SEED_DIR, 'index.json'),
    JSON.stringify({ chunks: [{ id: seed.chunk.id, name: seed.chunk.name, file: `${seed.chunk.id}.json` }] }, null, 2),
  )
  const written = JSON.parse(await readFile(jsonPath, 'utf8')) as WorldSeed
  return { jsonPath, bytes: Buffer.byteLength(text), written }
}

/** Coordinates at millimetre precision; the seed is served over the wire. */
function roundNumbers(_key: string, value: unknown): unknown {
  if (typeof value === 'number' && Number.isFinite(value) && !Number.isInteger(value)) {
    return Math.round(value * 1000) / 1000
  }
  return value
}

/**
 * §5's baseline table, as SQL. This is the "reality" side of the comparison and
 * nothing in the simulation may ever write to it, so it is emitted separately
 * from the runtime seed and can be loaded into Postgres independently.
 */
export async function emitSql(seed: WorldSeed, frame: ChunkFrame): Promise<string> {
  await mkdir(SQL_DIR, { recursive: true })
  const path = join(SQL_DIR, `${seed.chunk.id}.sql`)
  const lines: string[] = []

  lines.push('-- Generated by @civ/importer. Do not edit.')
  lines.push(`-- chunk: ${seed.chunk.id} (${seed.chunk.name})`)
  for (const p of seed.provenance) {
    lines.push(`-- ${p.layer}: ${p.source} — ${p.licence} (retrieved ${p.retrieved})`)
  }
  lines.push('')
  lines.push('begin;')
  lines.push(
    `insert into chunks (id, name, origin_lat, origin_lon, bbox) values ('${seed.chunk.id}', ${q(seed.chunk.name)}, ${seed.chunk.origin.lat}, ${seed.chunk.origin.lon}, ` +
      `st_makeenvelope(${seed.chunk.bbox[1]}, ${seed.chunk.bbox[0]}, ${seed.chunk.bbox[3]}, ${seed.chunk.bbox[2]}, 4326)) on conflict (id) do nothing;`,
  )
  lines.push('')

  lines.push(
    'insert into buildings_baseline (id, chunk_id, osm_id, bag_id, footprint, height_m, levels, construction_year, purpose, archetype, ground_m, name) values',
  )
  const rows = seed.buildings.map(
    (b) =>
      `  ('${b.id}', '${b.chunkId}', ${b.osmId ? `'${b.osmId}'` : 'null'}, ${b.bagId ? `'${b.bagId}'` : 'null'}, ` +
      `st_geomfromtext('${ringToWkt(frame, b.footprint)}', 4326), ${b.heightM.toFixed(2)}, ${b.levels}, ` +
      `${b.constructionYear ?? 'null'}, '${b.purpose}', '${b.archetype}', ${b.groundM.toFixed(2)}, ${b.name ? q(b.name) : 'null'})`,
  )
  lines.push(rows.join(',\n') + ';')
  lines.push('')

  lines.push('-- current state starts as an exact copy of the baseline (§5)')
  lines.push(
    `insert into buildings (id, baseline_id, source, chunk_id, parcel_id, footprint, height_m, levels, purpose, archetype, ground_m, condition, owner_id, state, progress, divergence, created_tick)`,
  )
  lines.push(
    `select gen_random_uuid(), b.id, 'real_world', b.chunk_id, null, b.footprint, b.height_m, b.levels, b.purpose, b.archetype, b.ground_m, 1.0, null, 'standing', 1.0, 0, 0 from buildings_baseline b where b.chunk_id = '${seed.chunk.id}';`,
  )
  lines.push('')
  lines.push('commit;')

  const text = lines.join('\n')
  await writeFile(path, text)
  return path
}

/**
 * §21.4 applied to the other emitter. The SQL is a lossier artifact than the
 * JSON: coordinates go through RD -> WGS84 with the Schreutelkamp/van Hees
 * polynomials and are then written at 8 decimal places, and heights are cut to
 * centimetres. None of that had a check on it, so this reads the file back,
 * projects every footprint vertex to local metres again, and reports the worst
 * round-trip error and any building that failed to make it into the file.
 */
export async function checkSql(
  path: string,
  seed: WorldSeed,
  frame: ChunkFrame,
): Promise<{ rows: number; missing: number; worstErrorM: number }> {
  const text = await readFile(path, 'utf8')
  const wkt = [...text.matchAll(/POLYGON\(\((.*?)\)\)/g)].map((m) => m[1])
  const byIndex = seed.buildings

  let worst = 0
  for (let i = 0; i < Math.min(wkt.length, byIndex.length); i++) {
    const pts = wkt[i]
      .split(',')
      .map((pair) => pair.trim().split(/\s+/).map(Number) as [number, number])
    const ring = byIndex[i].footprint
    for (let j = 0; j < ring.length; j++) {
      const [lon, lat] = pts[j]
      const [x, y] = frame.toLocal(lat, lon)
      worst = Math.max(worst, Math.hypot(x - ring[j][0], y - ring[j][1]))
    }
  }
  return { rows: wkt.length, missing: byIndex.length - wkt.length, worstErrorM: worst }
}

function q(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}
